<?php

namespace AppBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Class Configuration
 * @package AppBundle\DependencyInjection
 */
class Configuration implements ConfigurationInterface
{
    /**
     * Generates the configuration tree.
     *
     * @return TreeBuilder
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();

        $rootNode = $treeBuilder->root('app');

        $rootNode
            ->children()
                ->arrayNode('client')
                    ->children()
                        ->arrayNode('bitstamp')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                            ->children()
                                ->scalarNode('client_id')->end()
                            ->end()
                        ->end()
                        ->arrayNode('itbit')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                            ->children()
                                ->scalarNode('user_id')->end()
                            ->end()
                        ->end()
                        ->arrayNode('kraken')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                        ->end()
                        ->arrayNode('okcoin')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                        ->end()
                        ->arrayNode('binance')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                        ->end()
                        ->arrayNode('cexio')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                            ->children()
                                ->scalarNode('user_id')->end()
                            ->end()
                        ->end()
                        ->arrayNode('bittrex')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                        ->end()
                        ->arrayNode('quadrigacx')
                            ->children()
                                ->scalarNode('enable')->end()
                            ->end()
                            ->children()
                                ->scalarNode('base_uri')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_key')->end()
                            ->end()
                            ->children()
                                ->scalarNode('api_secret')->end()
                            ->end()
                            ->children()
                                ->scalarNode('client_id')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
